// generated by scripts/generate-byte-tables.js — do not edit manually
// chardet e9603fad69cd, python 3.11.15
//
// Per-encoding single-byte decode tables for every encoding in the
// registry (and cp037, which markup.ts decodes with by name), computed by
// Python's codecs + unicodedata (the source of truth). byte-decode.ts is
// the lookup API over them; read it rather than these strings directly.
//   cps        charCodeAt(b) = the decoded code point of byte b, or 0xFFFF
//              when the byte does not decode, or 0xFFFE when it decodes to
//              zero or more than one character (a stateful codec's shift
//              byte).
//   cats       charCodeAt(b) - CAT_BASE = the index into CATEGORY_NAMES of
//              byte b's Unicode general category; 'Cn' for the two
//              sentinel cases.
//   singleByte true for a stateless single-byte codec — every byte decodes
//              to exactly one character or is undefined — so that "data
//              decodes" is exactly "no byte of data is undefined". False
//              for the multi-byte encodings and the UTF family.
// ASCII_CPS / ASCII_CATS are the low half (0x00..0x7F) every
// ASCII-compatible encoding shares.
export interface ByteDecodeTable {
  readonly singleByte: boolean;
  readonly cps: string;
  readonly cats: string;
}
export const CATEGORY_NAMES: readonly string[] = ["Lu","Ll","Lt","Lm","Lo","Mn","Mc","Me","Nd","Nl","No","Pc","Pd","Ps","Pe","Pi","Pf","Po","Sm","Sc","Sk","So","Zs","Zl","Zp","Cc","Cf","Cs","Co","Cn"];
export const CAT_BASE = 0x30;
const ASCII_CPS = "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~";
const ASCII_CATS = "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>BI";
export const BYTE_DECODE_TABLES: Readonly<Record<string, ByteDecodeTable>> = Object.freeze({
  "ascii": {
    singleByte: true,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "big5hkscs": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "cp1006": {
    singleByte: true,
    cps: ASCII_CPS + " ۰۱۲۳۴۵۶۷۸۹،؛­؟ﺁﺍﺎﺎﺏﺑﭖﭘﺓﺕﺗﭦﭨﺙﺛﺝﺟﭺﭼﺡﺣﺥﺧﺩﮄﺫﺭﮌﺯﮊﺱﺳﺵﺷﺹﺻﺽﺿﻁﻅﻉﻊﻋﻌﻍﻎﻏﻐﻑﻓﻕﻗﻙﻛﮒﮔﻝﻟﻠﻡﻣﮞﻥﻧﺅﻭﮦﮨﮩﮪﺀﺉﺊﺋﻱﻲﻳﮰﮮﹼﹽ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF8888888888AAJA444444444444444444444444444444444444444444444444444444444444444444444444444444444",
  },
  "cp1026": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a  âäàáãå{ñÇ.<(+!&éêëèíîïìßĞİ*);^-/ÂÄÀÁÃÅ[Ñş,%_>?øÉÊËÈÍÎÏÌı:ÖŞ'=ÜØabcdefghi«»}`¦±°jklmnopqrªºæ¸Æ¤µöstuvwxyz¡¿]$@®¢£¥·©§¶¼½¾¬|¯¨´×çABCDEFGHI­ô~òóõğJKLMNOPQR¹û\\ùúÿü÷STUVWXYZ²Ô#ÒÓÕ0123456789³Û\"ÙÚ",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFF111111=10AB=BAA11111111100A>AD<A000000=01AA;BA1000000001A00AB00111111111?@>DEBE111111111441D0C1111111111AA>CAECCCAEAA:::BBDDDB1000000000J1B1111000000000:1A1111B00000000:0A0008888888888:0A00I",
  },
  "cp1125": {
    singleByte: true,
    cps: ASCII_CPS + "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмноп░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀рстуфхцчшщъыьэюяЁёҐґЄєІіЇї·√№¤■ ",
    cats: ASCII_CATS + "000000000000000000000000000000001111111111111111EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE11111111111111110101010101ABECEF",
  },
  "cp1140": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a  âäàáãåçñ¢.<(+|&éêëèíîïìß!$*);¬-/ÂÄÀÁÃÅÇÑ¦,%_>?øÉÊËÈÍÎÏÌ`:#@'=\"Øabcdefghi«»ðýþ±°jklmnopqrªºæ¸Æ€µ~stuvwxyz¡¿ÐÝÞ®^£¥·©§¶¼½¾[]¯¨´×{ABCDEFGHI­ôöòóõ}JKLMNOPQR¹ûüùúÿ\\÷STUVWXYZ²ÔÖÒÓÕ0123456789³ÛÜÙÚ",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFF11111111CAB=BBA111111111ACA>AB<A00000000EAA;BA100000000DAAAABA0111111111?@111BE111111111441D0C1B11111111AA000EDCCAEAA:::=>DDDB=000000000J11111>000000000:11111AB00000000:000008888888888:0000I",
  },
  "cp1250": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚￿„…†‡￿‰Š‹ŚŤŽŹ￿‘’“”•–—￿™š›śťžź ˇ˘Ł¤Ą¦§¨©Ş«¬­®Ż°±˛ł´µ¶·¸ąş»Ľ˝ľżŔÁÂĂÄĹĆÇČÉĘËĚÍÎĎĐŃŇÓÔŐÖ×ŘŮÚŰÜÝŢßŕáâăäĺćçčéęëěíîďđńňóôőö÷řůúűüýţ˙",
    cats: ASCII_CATS + "CM=M=AAAMA0?0000M?@?@A<<ME1@1111F3D0C0EADE0?BJE0EBD1D1AAD11@0D1100000000000000000000000B0000000111111111111111111111111B1111111D",
  },
  "cp1251": {
    singleByte: true,
    cps: ASCII_CPS + "ЂЃ‚ѓ„…†‡€‰Љ‹ЊЌЋЏђ‘’“”•–—￿™љ›њќћџ ЎўЈ¤Ґ¦§Ё©Є«¬­®Ї°±Ііґµ¶·ё№є»јЅѕїАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя",
    cats: ASCII_CATS + "00=1=AAACA0?00001?@?@A<<ME1@1111F010C0EA0E0?BJE0EB0111AA1E1@10110000000000000000000000000000000011111111111111111111111111111111",
  },
  "cp1252": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚ƒ„…†‡ˆ‰Š‹Œ￿Ž￿￿‘’“”•–—˜™š›œ￿žŸ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ",
    cats: ASCII_CATS + "CM=1=AAA3A0?0M0MM?@?@A<<DE1@1M10FACCCCEADE4?BJEDEB::D1AAD:4@:::A00000000000000000000000B0000000111111111111111111111111B11111111",
  },
  "cp1253": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚ƒ„…†‡￿‰￿‹￿￿￿￿￿‘’“”•–—￿™￿›￿￿￿￿ ΅Ά£¤¥¦§¨©￿«¬­®―°±²³΄µ¶·ΈΉΊ»Ό½ΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡ￿ΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώ￿",
    cats: ASCII_CATS + "CM=1=AAAMAM?MMMMM?@?@A<<MEM@MMMMFD0CCCEADEM?BJE<EB::D1AA000@0:00100000000000000000M00000000011111111111111111111111111111111111M",
  },
  "cp1254": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚ƒ„…†‡ˆ‰Š‹Œ￿￿￿￿‘’“”•–—˜™š›œ￿￿Ÿ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚÛÜİŞßàáâãäåæçèéêëìíîïğñòóôõö÷øùúûüışÿ",
    cats: ASCII_CATS + "CM=1=AAA3A0?0MMMM?@?@A<<DE1@1MM0FACCCCEADE4?BJEDEB::D1AAD:4@:::A00000000000000000000000B0000000111111111111111111111111B11111111",
  },
  "cp1255": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚ƒ„…†‡ˆ‰￿‹￿￿￿￿￿‘’“”•–—˜™￿›￿￿￿￿ ¡¢£₪¥¦§¨©×«¬­®¯°±²³´µ¶·¸¹÷»¼½¾¿ְֱֲֳִֵֶַָֹ￿ֻּֽ־ֿ׀ׁׂ׃װױײ׳״￿￿￿￿￿￿￿אבגדהוזחטיךכלםמןנסעףפץצקרשת￿￿‎‏￿",
    cats: ASCII_CATS + "CM=1=AAA3AM?MMMMM?@?@A<<DEM@MMMMFACCCCEADEB?BJEDEB::D1AAD:B@:::A5555555555M555<5A55A444AAMMMMMMM444444444444444444444444444MMJJM",
  },
  "cp1256": {
    singleByte: true,
    cps: ASCII_CPS + "€پ‚ƒ„…†‡ˆ‰ٹ‹Œچژڈگ‘’“”•–—ک™ڑ›œ‌‍ں ،¢£¤¥¦§¨©ھ«¬­®¯°±²³´µ¶·¸¹؛»¼½¾؟ہءآأؤإئابةتثجحخدذرزسشصض×طظعغـفقكàلâمنهوçèéêëىيîïًٌٍَôُِ÷ّùْûü‎‏ے",
    cats: ASCII_CATS + "C4=1=AAA3A4?04444?@?@A<<4E4@1JJ4FACCCCEADE4?BJEDEB::D1AAD:A@:::A44444444444444444444444B4444344414144441111144115555155B51511JJ4",
  },
  "cp1257": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚￿„…†‡￿‰￿‹￿¨ˇ¸￿‘’“”•–—￿™￿›￿¯˛￿ ￿¢£¤￿¦§Ø©Ŗ«¬­®Æ°±²³´µ¶·ø¹ŗ»¼½¾æĄĮĀĆÄÅĘĒČÉŹĖĢĶĪĻŠŃŅÓŌÕÖ×ŲŁŚŪÜŻŽßąįāćäåęēčéźėģķīļšńņóōõö÷ųłśūüżž˙",
    cats: ASCII_CATS + "CM=M=AAAMAM?MD3DM?@?@A<<MEM@MDDMFMCCCMEA0E0?BJE0EB::D1AA1:1@:::100000000000000000000000B0000000111111111111111111111111B1111111D",
  },
  "cp1258": {
    singleByte: true,
    cps: ASCII_CPS + "€￿‚ƒ„…†‡ˆ‰￿‹Œ￿￿￿￿‘’“”•–—˜™￿›œ￿￿Ÿ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂĂÄÅÆÇÈÉÊË̀ÍÎÏĐÑ̉ÓÔƠÖ×ØÙÚÛÜỮßàáâăäåæçèéêë́íîïđṇ̃óôơö÷øùúûüư₫ÿ",
    cats: ASCII_CATS + "CM=1=AAA3AM?0MMMM?@?@A<<DEM@1MM0FACCCCEADE4?BJEDEB::D1AAD:4@:::A00000000000050000050000B0000005111111111111151111151111B111111C1",
  },
  "cp273": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a  â{àáãåçñÄ.<(+!&éêëèíîïì~Ü$*);^-/Â[ÀÁÃÅÇÑö,%_>?øÉÊËÈÍÎÏÌ`:#§'=\"Øabcdefghi«»ðýþ±°jklmnopqrªºæ¸Æ¤µßstuvwxyz¡¿ÐÝÞ®¢£¥·©@¶¼½¾¬|‾¨´×äABCDEFGHI­ô¦òóõüJKLMNOPQR¹û}ùúÿÖ÷STUVWXYZ²Ô\\ÒÓÕ0123456789³Û]ÙÚ",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFF1=1111110AB=BAA11111111B0CA>AD<A0=0000001AA;BA100000000DAAAABA0111111111?@111BE111111111441D0C1111111111AA000ECCCAEAA:::BBADDB1000000000J1E1111000000000:1>1110B00000000:0A0008888888888:0>00I",
  },
  "cp424": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a אבגדהוזחט¢.<(+|&יךכלםמןנס!$*);¬-/עףפץצקרש¦,%_>?￿ת￿￿ ￿￿￿‗`:#@'=\"￿abcdefghi«»￿￿￿±°jklmnopqr￿￿￿¸￿¤µ~stuvwxyz￿￿￿￿￿®^£¥·©§¶¼½¾[]¯¨´×{ABCDEFGHI­￿￿￿￿￿}JKLMNOPQR¹￿￿￿￿￿\\÷STUVWXYZ²￿￿￿￿￿0123456789³￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF444444444CAB=BBA444444444ACA>AB<A44444444EAA;BAM4MMFMMMADAAAABAM111111111?@MMMBE111111111MMMDMC1B11111111MMMMMEDCCAEAA:::=>DDDB=000000000JMMMMM>000000000:MMMMMAB00000000:MMMMM8888888888:MMMMI",
  },
  "cp437": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "011111111111110001011111100CCCC111111044AEB::A?@EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE110101110001B11BBBBBBBBBEBAB3:EF",
  },
  "cp500": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a  âäàáãåçñ[.<(+!&éêëèíîïìß]$*);^-/ÂÄÀÁÃÅÇÑ¦,%_>?øÉÊËÈÍÎÏÌ`:#@'=\"Øabcdefghi«»ðýþ±°jklmnopqrªºæ¸Æ¤µ~stuvwxyz¡¿ÐÝÞ®¢£¥·©§¶¼½¾¬|¯¨´×{ABCDEFGHI­ôöòóõ}JKLMNOPQR¹ûüùúÿ\\÷STUVWXYZ²ÔÖÒÓÕ0123456789³ÛÜÙÚ",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFF11111111=AB=BAA111111111>CA>AD<A00000000EAA;BA100000000DAAAABA0111111111?@111BE111111111441D0C1B11111111AA000ECCCAEAA:::BBDDDB=000000000J11111>000000000:11111AB00000000:000008888888888:0000I",
  },
  "cp720": {
    singleByte: true,
    cps: ASCII_CPS + "éâàçêëèïîّْô¤ـûùءآأؤ£إئابةتثجحخدذرزسشص«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀ضطظعغفµقكلمنهوىي≡ًٌٍَُِ≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "II11I1I111111IIII551C3114444C44444444444444444?@EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE4444441444444444B555555BEBAB3:EF",
  },
  "cp737": {
    singleByte: true,
    cps: ASCII_CPS + "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρσςτυφχψ░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀ωάέήϊίόύϋώΆΈΉΊΌΎΏ±≥≤ΪΫ÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "000000000000000000000000111111111111111111111111EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE11111111110000000BBB00BBEBAB3:EF",
  },
  "cp775": {
    singleByte: true,
    cps: ASCII_CPS + "ĆüéāäģåćłēŖŗīŹÄÅÉæÆōöĢ¢ŚśÖÜø£Ø×¤ĀĪóŻżź”¦©®¬½¼Ł«»░▒▓│┤ĄČĘĖ╣║╗╝ĮŠ┐└┴┬├─┼ŲŪ╚╔╩╦╠═╬Žąčęėįšųūž┘┌█▄▌▐▀ÓßŌŃõÕµńĶķĻļņĒŅ’­±“¾¶§÷„°∙·¹³²■ ",
    cats: ASCII_CATS + "0111111111011000010110C01001C0BC001011@EEEB::0?@EEEEE0000EEEE00EEEEEEE00EEEEEEE0111111111EEEEEEE010010110101100@JB?:AAB=EBA:::EF",
  },
  "cp850": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜø£Ø×ƒáíóúñÑªº¿®¬½¼¡«»░▒▓│┤ÁÂÀ©╣║╗╝¢¥┐└┴┬├─┼ãÃ╚╔╩╦╠═╬¤ðÐÊËÈıÍÎÏ┘┌█▄¦Ì▀ÓßÔÒõÕµþÞÚÛÙýÝ¯´­±‗¾¶§÷¸°¨·¹³²■ ",
    cats: ASCII_CATS + "0111111111111100010111111001C0B111111044AEB::A?@EEEEE000EEEEECCEEEEEEE10EEEEEEEC100001000EEEEE0E01001011000010DDJBA:AABDEDA:::EF",
  },
  "cp852": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäůćçłëŐőîŹÄĆÉĹĺôöĽľŚśÖÜŤťŁ×čáíóúĄąŽžĘę¬źČş«»░▒▓│┤ÁÂĚŞ╣║╗╝Żż┐└┴┬├─┼Ăă╚╔╩╦╠═╬¤đĐĎËďŇÍÎě┘┌█▄ŢŮ▀ÓßÔŃńňŠšŔÚŕŰýÝţ´­˝˛ˇ˘§÷¸°¨˙űŘř■ ",
    cats: ASCII_CATS + "011111111101100000111010100010B11111010101B101?@EEEEE0000EEEE01EEEEEEE01EEEEEEEC100010001EEEE00E010011010010101DJDD3DABDEDD101EF",
  },
  "cp855": {
    singleByte: true,
    cps: ASCII_CPS + "ђЂѓЃёЁєЄѕЅіІїЇјЈљЉњЊћЋќЌўЎџЏюЮъЪаАбБцЦдДеЕфФгГ«»░▒▓│┤хХиИ╣║╗╝йЙ┐└┴┬├─┼кК╚╔╩╦╠═╬¤лЛмМнНоОп┘┌█▄Пя▀ЯрРсСтТуУжЖвВьЬ№­ыЫзЗшШэЭщЩчЧ§■ ",
    cats: ASCII_CATS + "1010101010101010101010101010101010101010101010?@EEEEE1010EEEE10EEEEEEE10EEEEEEEC101010101EEEE01E010101010101010EJ101010101010AEF",
  },
  "cp856": {
    singleByte: true,
    cps: ASCII_CPS + "אבגדהוזחטיךכלםמןנסעףפץצקרשת￿£￿×￿￿￿￿￿￿￿￿￿￿®¬½¼￿«»░▒▓│┤￿￿￿©╣║╗╝¢¥┐└┴┬├─┼￿￿╚╔╩╦╠═╬¤￿￿￿￿￿￿￿￿￿┘┌█▄¦￿▀￿￿￿￿￿￿µ￿￿￿￿￿￿￿¯´­±‗¾¶§÷¸°¨·¹³²■ ",
    cats: ASCII_CATS + "444444444444444444444444444MCMBMMMMMMMMMMEB::M?@EEEEEMMMEEEEECCEEEEEEEMMEEEEEEECMMMMMMMMMEEEEEMEMMMMMM1MMMMMMMDDJBA:AABDEDA:::EF",
  },
  "cp857": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäàåçêëèïîıÄÅÉæÆôöòûùİÖÜø£ØŞşáíóúñÑĞğ¿®¬½¼¡«»░▒▓│┤ÁÂÀ©╣║╗╝¢¥┐└┴┬├─┼ãÃ╚╔╩╦╠═╬¤ºªÊËÈ￿ÍÎÏ┘┌█▄¦Ì▀ÓßÔÒõÕµ￿×ÚÛÙìÿ¯´­±￿¾¶§÷¸°¨·¹³²■ ",
    cats: ASCII_CATS + "0111111111111100010111110001C00111111001AEB::A?@EEEEE000EEEEECCEEEEEEE10EEEEEEEC44000M000EEEEE0E0100101MB00011DDJBM:AABDEDA:::EF",
  },
  "cp858": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜø£Ø×ƒáíóúñÑªº¿®¬½¼¡«»░▒▓│┤ÁÂÀ©╣║╗╝¢¥┐└┴┬├─┼ãÃ╚╔╩╦╠═╬¤ðÐÊËÈ€ÍÎÏ┘┌█▄¦Ì▀ÓßÔÒõÕµþÞÚÛÙýÝ¯´­±‗¾¶§÷¸°¨·¹³²■ ",
    cats: ASCII_CATS + "0111111111111100010111111001C0B111111044AEB::A?@EEEEE000EEEEECCEEEEEEE10EEEEEEEC10000C000EEEEE0E01001011000010DDJBA:AABDEDA:::EF",
  },
  "cp860": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâãàÁçêÊèÍÔìÃÂÉÀÈôõòÚùÌÕÜ¢£Ù₧ÓáíóúñÑªº¿Ò¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "011111011010010000011101000CC0C011111044A0B::A?@EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE110101110001B11BBBBBBBBBEBAB3:EF",
  },
  "cp861": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäàåçêëèÐðÞÄÅÉæÆôöþûÝýÖÜø£Ø₧ƒáíóúÁÍÓÚ¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "0111111111101000010111101001C0C111110000AEB::A?@EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE110101110001B11BBBBBBBBBEBAB3:EF",
  },
  "cp862": {
    singleByte: true,
    cps: ASCII_CPS + "אבגדהוזחטיךכלםמןנסעףפץצקרשת¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "444444444444444444444444444CCCC111111044AEB::A?@EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE110101110001B11BBBBBBBBBEBAB3:EF",
  },
  "cp863": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâÂà¶çêëèïî‗À§ÉÈÊôËÏûù¤ÔÜ¢£ÙÛƒ¦´óú¨¸³¯Î⌐¬½¼¾«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "011101A111111A0A00010011C00CC001ED11DD:D0EB:::?@EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE110101110001B11BBBBBBBBBEBAB3:EF",
  },
  "cp864": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$٪&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°·∙√▒─│┼┤┬├┴┐┌└┘β∞φ±½¼≈«»ﻷﻸ￿￿ﻻﻼ￿ ­ﺂ£¤ﺄ￿￿ﺎﺏﺕﺙ،ﺝﺡﺥ٠١٢٣٤٥٦٧٨٩ﻑ؛ﺱﺵﺹ؟¢ﺀﺁﺃﺅﻊﺋﺍﺑﺓﺗﺛﺟﺣﺧﺩﺫﺭﺯﺳﺷﺻﺿﻁﻅﻋﻏ¦¬÷×ﻉـﻓﻗﻛﻟﻣﻧﻫﻭﻯﻳﺽﻌﻎﻍﻡﹽّﻥﻩﻬﻰﻲﻐﻕﻵﻶﻝﻙﻱ■￿",
    cats: ASCII_CATS + "EABBEEEEEEEEEEEE1B1B::B?@44MM44MFJ4CC4MM4444A44488888888884A444AC44444444444444444444444444EBBB4344444444444444445444444444444EM",
  },
  "cp865": {
    singleByte: true,
    cps: ASCII_CPS + "ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜø£Ø₧ƒáíóúñÑªº¿⌐¬½¼¡«¤░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ",
    cats: ASCII_CATS + "0111111111111100010111111001C0C111111044AEB::A?CEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE110101110001B11BBBBBBBBBEBAB3:EF",
  },
  "cp866": {
    singleByte: true,
    cps: ASCII_CPS + "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмноп░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀рстуфхцчшщъыьэюяЁёЄєЇїЎў°∙·√№¤■ ",
    cats: ASCII_CATS + "000000000000000000000000000000001111111111111111EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE111111111111111101010101EBABECEF",
  },
  "cp869": {
    singleByte: true,
    cps: ASCII_CPS + "￿￿￿￿￿￿Ά￿·¬¦‘’Έ―ΉΊΪΌ￿￿ΎΫ©Ώ²³ά£έήίϊΐόύΑΒΓΔΕΖΗ½ΘΙ«»░▒▓│┤ΚΛΜΝ╣║╗╝ΞΟ┐└┴┬├─┼ΠΡ╚╔╩╦╠═╬ΣΤΥΦΧΨΩαβγ┘┌█▄δε▀ζηθικλμνξοπρσςτ΄­±υφχ§ψ΅°¨ωϋΰώ■ ",
    cats: ASCII_CATS + "MMMMMM0MABE?@0<0000MM00E0::1C11111110000000:00?@EEEEE0000EEEE00EEEEEEE00EEEEEEE0000000111EEEE11E111111111111111DJB111A1DED1111EF",
  },
  "cp874": {
    singleByte: true,
    cps: ASCII_CPS + "€￿￿￿￿…￿￿￿￿￿￿￿￿￿￿￿‘’“”•–—￿￿￿￿￿￿￿￿ กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลฦวศษสหฬอฮฯะัาำิีึืฺุู￿￿￿￿฿เแโใไๅๆ็่้๊๋์ํ๎๏๐๑๒๓๔๕๖๗๘๙๚๛￿￿￿￿",
    cats: ASCII_CATS + "CMMMMAMMMMMMMMMMM?@?@A<<MMMMMMMMF4444444444444444444444444444444444444444444444445445555555MMMMC444444355555555A8888888888AAMMMM",
  },
  "cp875": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a ΑΒΓΔΕΖΗΘΙ[.<(+!&ΚΛΜΝΞΟΠΡΣ]$*);^-/ΤΥΦΧΨΩΪΫ|,%_>?¨ΆΈΉ ΊΌΎΏ`:#@'=\"΅abcdefghiαβγδεζ°jklmnopqrηθικλμ´~stuvwxyzνξοπρσ£άέήϊίόύϋώςτυφχψ{ABCDEFGHI­ωΐΰ‘―}JKLMNOPQR±½\u001a·’¦\\\u001aSTUVWXYZ²§\u001a\u001a«¬0123456789³©\u001a\u001a»",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF000000000=AB=BAA000000000>CA>AD<A00000000BAA;BAD000F0000DAAAABAD111111111111111E111111111111111DB11111111111111C111111111111111=000000000J111?<>000000000B:IA@EAI00000000:AII?B8888888888:EII@I",
  },
  "cp932": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿｡｢｣､･ｦｧｨｩｪｫｬｭｮｯｰｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝﾞﾟ￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLA=>AA4444444444344444444444444444444444444444444444444444444433MMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLL",
  },
  "cp949": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "euc_jis_2004": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "euc_kr": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "gb18030": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "hp-roman8": {
    singleByte: true,
    cps: ASCII_CPS + " ÀÂÈÊËÎÏ´ˋˆ¨˜ÙÛ₤¯Ýý°ÇçÑñ¡¿¤£¥§ƒ¢âêôûáéóúàèòùäëöüÅîØÆåíøæÄìÖÜÉïßÔÁÃãÐðÍÌÓÒÕõŠšÚŸÿÞþ·µ¶¾—¼½ªº«■»±￿",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF0000000D33DD00CD01E0101AACCCA1C11111111111111110100111101000110001010000010100101A1A:<::44?E@BM",
  },
  "hz": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>MIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "iso2022_jp_2": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a￿\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIMIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>BIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "iso2022_jp_2004": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a￿\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIMIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>BIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "iso2022_jp_ext": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a￿\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIMIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>BIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "iso2022_kr": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r￾￾\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a￿\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIMMIIIIIIIIIIIMIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>BIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "iso8859-1": {
    singleByte: true,
    cps: ASCII_CPS + " ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFACCCCEADE4?BJEDEB::D1AAD:4@:::A00000000000000000000000B0000000111111111111111111111111B11111111",
  },
  "iso8859-10": {
    singleByte: true,
    cps: ASCII_CPS + " ĄĒĢĪĨĶ§ĻĐŠŦŽ­ŪŊ°ąēģīĩķ·ļđšŧž―ūŋĀÁÂÃÄÅÆĮČÉĘËĖÍÎÏÐŅŌÓÔÕÖŨØŲÚÛÜÝÞßāáâãäåæįčéęëėíîïðņōóôõöũøųúûüýþĸ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF000000A00000J00E111111A11111<110000000000000000000000000000000111111111111111111111111111111111",
  },
  "iso8859-13": {
    singleByte: true,
    cps: ASCII_CPS + " ”¢£¤„¦§Ø©Ŗ«¬­®Æ°±²³“µ¶·ø¹ŗ»¼½¾æĄĮĀĆÄÅĘĒČÉŹĖĢĶĪĻŠŃŅÓŌÕÖ×ŲŁŚŪÜŻŽßąįāćäåęēčéźėģķīļšńņóōõö÷ųłśūüżž’",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF@CCC=EA0E0?BJE0EB::?1AA1:1@:::100000000000000000000000B0000000111111111111111111111111B1111111@",
  },
  "iso8859-14": {
    singleByte: true,
    cps: ASCII_CPS + " Ḃḃ£ĊċḊ§Ẁ©ẂḋỲ­®ŸḞḟĠġṀṁ¶ṖẁṗẃṠỳẄẅṡÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏŴÑÒÓÔÕÖṪØÙÚÛÜÝŶßàáâãäåæçèéêëìíîïŵñòóôõöṫøùúûüýŷÿ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF01C010A0E010JE0010101A0111010110000000000000000000000000000000111111111111111111111111111111111",
  },
  "iso8859-15": {
    singleByte: true,
    cps: ASCII_CPS + " ¡¢£€¥Š§š©ª«¬­®¯°±²³Žµ¶·ž¹º»ŒœŸ¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFACCCC0A1E4?BJEDEB::01AA1:4@010A00000000000000000000000B0000000111111111111111111111111B11111111",
  },
  "iso8859-16": {
    singleByte: true,
    cps: ASCII_CPS + " ĄąŁ€„Š§š©Ș«Ź­źŻ°±ČłŽ”¶·žčș»ŒœŸżÀÁÂĂÄĆÆÇÈÉÊËÌÍÎÏĐŃÒÓÔŐÖŚŰÙÚÛÜĘȚßàáâăäćæçèéêëìíîïđńòóôőöśűùúûüęțÿ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF010C=0A1E0?0J10EB010@AA111@01010000000000000000000000000000000111111111111111111111111111111111",
  },
  "iso8859-2": {
    singleByte: true,
    cps: ASCII_CPS + " Ą˘Ł¤ĽŚ§¨ŠŞŤŹ­ŽŻ°ą˛ł´ľśˇ¸šşťź˝žżŔÁÂĂÄĹĆÇČÉĘËĚÍÎĎĐŃŇÓÔŐÖ×ŘŮÚŰÜÝŢßŕáâăäĺćçčéęëěíîďđńňóôőö÷řůúűüýţ˙",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF0D0C00AD0000J00E1D1D113D1111D1100000000000000000000000B0000000111111111111111111111111B1111111D",
  },
  "iso8859-3": {
    singleByte: true,
    cps: ASCII_CPS + " Ħ˘£¤￿Ĥ§¨İŞĞĴ­￿Ż°ħ²³´µĥ·¸ışğĵ½￿żÀÁÂ￿ÄĊĈÇÈÉÊËÌÍÎÏ￿ÑÒÓÔĠÖ×ĜÙÚÛÜŬŜßàáâ￿äċĉçèéêëìíîï￿ñòóôġö÷ĝùúûüŭŝ˙",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF0DCCM0AD0000JM0E1::D11AD1111:M1000M000000000000M000000B00000001111M111111111111M111111B1111111D",
  },
  "iso8859-4": {
    singleByte: true,
    cps: ASCII_CPS + " ĄĸŖ¤ĨĻ§¨ŠĒĢŦ­Ž¯°ą˛ŗ´ĩļˇ¸šēģŧŊžŋĀÁÂÃÄÅÆĮČÉĘËĖÍÎĪĐŅŌĶÔÕÖ×ØŲÚÛÜŨŪßāáâãäåæįčéęëėíîīđņōķôõö÷øųúûüũū˙",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF010C00AD0000J0DE1D1D113D111101100000000000000000000000B0000000111111111111111111111111B1111111D",
  },
  "iso8859-5": {
    singleByte: true,
    cps: ASCII_CPS + " ЁЂЃЄЅІЇЈЉЊЋЌ­ЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя№ёђѓєѕіїјљњћќ§ўџ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF000000000000J000000000000000000000000000000000011111111111111111111111111111111E111111111111A11",
  },
  "iso8859-6": {
    singleByte: true,
    cps: ASCII_CPS + " ￿￿￿¤￿￿￿￿￿￿￿،­￿￿￿￿￿￿￿￿￿￿￿￿￿؛￿￿￿؟￿ءآأؤإئابةتثجحخدذرزسشصضطظعغ￿￿￿￿￿ـفقكلمنهوىيًٌٍَُِّْ￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFMMMCMMMMMMMAJMMMMMMMMMMMMMAMMMAM44444444444444444444444444MMMMM3444444444455555555MMMMMMMMMMMMM",
  },
  "iso8859-7": {
    singleByte: true,
    cps: ASCII_CPS + " ‘’£€₯¦§¨©ͺ«¬­￿―°±²³΄΅Ά·ΈΉΊ»Ό½ΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡ￿ΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώ￿",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIF?@CCCEADE3?BJM<EB::DD0A000@0:00100000000000000000M00000000011111111111111111111111111111111111M",
  },
  "iso8859-8": {
    singleByte: true,
    cps: ASCII_CPS + " ￿¢£¤¥¦§¨©×«¬­®¯°±²³´µ¶·¸¹÷»¼½¾￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿‗אבגדהוזחטיךכלםמןנסעףפץצקרשת￿￿‎‏￿",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFMCCCCEADEB?BJEDEB::D1AAD:B@:::MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMA444444444444444444444444444MMJJM",
  },
  "iso8859-9": {
    singleByte: true,
    cps: ASCII_CPS + " ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚÛÜİŞßàáâãäåæçèéêëìíîïğñòóôõö÷øùúûüışÿ",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFACCCCEADE4?BJEDEB::D1AAD:4@:::A00000000000000000000000B0000000111111111111111111111111B11111111",
  },
  "johab": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "koi8-r": {
    singleByte: true,
    cps: ASCII_CPS + "─│┌┐└┘├┤┬┴┼▀▄█▌▐░▒▓⌠■∙√≈≤≥ ⌡°²·÷═║╒ё╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡Ё╢╣╤╥╦╧╨╩╪╫╬©юабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ",
    cats: ASCII_CATS + "EEEEEEEEEEEEEEEEEEEBEBBBBBFBE:ABEEE1EEEEEEEEEEEEEEE0EEEEEEEEEEEE1111111111111111111111111111111100000000000000000000000000000000",
  },
  "koi8-t": {
    singleByte: true,
    cps: ASCII_CPS + "қғ‚Ғ„…†‡￿‰ҳ‹ҲҷҶ￿Қ‘’“”•–—￿™￿›￿￿￿￿￿ӯӮё¤ӣ¦§￿￿￿«¬­®￿°±²Ё￿Ӣ¶·￿№￿»￿￿￿©юабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ",
    cats: ASCII_CATS + "11=0=AAAMA1?010M0?@?@A<<MEM@MMMMM101C1EAMMM?BJEMEB:0M0AAMEM@MMME1111111111111111111111111111111100000000000000000000000000000000",
  },
  "koi8-u": {
    singleByte: true,
    cps: ASCII_CPS + "─│┌┐└┘├┤┬┴┼▀▄█▌▐░▒▓⌠■∙√≈≤≥ ⌡°²·÷═║╒ёє╔ії╗╘╙╚╛ґ╝╞╟╠╡ЁЄ╣ІЇ╦╧╨╩╪Ґ╬©юабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ",
    cats: ASCII_CATS + "EEEEEEEEEEEEEEEEEEEBEBBBBBFBE:ABEEE11E11EEEEE1EEEEE00E00EEEEE0EE1111111111111111111111111111111100000000000000000000000000000000",
  },
  "kz1048": {
    singleByte: true,
    cps: ASCII_CPS + "ЂЃ‚ѓ„…†‡€‰Љ‹ЊҚҺЏђ‘’“”•–—￿™љ›њқһџ ҰұӘ¤Ө¦§Ё©Ғ«¬­®Ү°±Ііөµ¶·ё№ғ»әҢңүАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя",
    cats: ASCII_CATS + "00=1=AAACA0?00001?@?@A<<ME1@1111F010C0EA0E0?BJE0EB0111AA1E1@10110000000000000000000000000000000011111111111111111111111111111111",
  },
  "mac-cyrillic": {
    singleByte: true,
    cps: ASCII_CPS + "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ†°Ґ£§•¶І®©™Ђђ≠Ѓѓ∞±≤≥іµґЈЄєЇїЉљЊњјЅ¬√ƒ≈∆«»… ЋћЌќѕ–—“”‘’÷„ЎўЏџ№Ёёяабвгдежзийклмнопрстуфхцчшщъыьэю€",
    cats: ASCII_CATS + "00000000000000000000000000000000AE0CAAA0EEE01B01BBBB11100101010110BB1BB?@AF01011<<?@?@B=0101E0111111111111111111111111111111111C",
  },
  "mac-greek": {
    singleByte: true,
    cps: ASCII_CPS + "Ä¹²É³ÖÜ΅àâä΄¨çéèêë£™îï•½‰ôö¦€ùûü†ΓΔΘΛΞΠß®©ΣΪ§≠°·Α±≤≥¥ΒΕΖΗΙΚΜΦΫΨΩάΝ¬ΟΡ≈Τ«»… ΥΧΆΈœ–―“”‘’÷ΉΊΌΎέήίόΏύαβψδεφγηιξκλμνοπώρστθωςχυζϊϋΐΰ­",
    cats: ASCII_CATS + "0::0:00D111DD11111CE11A:A11EC111A0000001EE00ABEA0BBBC0000000000010B00B0?@AF00001<<?@?@B0000111101111111111111111111111111111111J",
  },
  "mac-iceland": {
    singleByte: true,
    cps: ASCII_CPS + "ÄÅÇÉÑÖÜáàâäãåçéèêëíìîïñóòôöõúùûüÝ°¢£§•¶ß®©™´¨≠ÆØ∞±≤≥¥µ∂∑∏π∫ªºΩæø¿¡¬√ƒ≈∆«»… ÀÃÕŒœ–—“”‘’÷◊ÿŸ⁄€ÐðÞþý·‚„‰ÂÊÁËÈÍÎÏÌÓÔÒÚÛÙıˆ˜¯˘˙˚¸˝˛ˇ",
    cats: ASCII_CATS + "000000011111111111111111111111110ECCAAA1EEEDDB00BBBBC1BBB1B44011AABB1BB?@AF00001<<?@?@BE10BC01011A==A00000000000L000013DDDDDDDD3",
  },
  "mac-latin2": {
    singleByte: true,
    cps: ASCII_CPS + "ÄĀāÉĄÖÜáąČäčĆćéŹźĎíďĒēĖóėôöõúĚěü†°Ę£§•¶ß®©™ę¨≠ģĮįĪ≤≥īĶ∂∑łĻļĽľĹĺŅņŃ¬√ńŇ∆«»… ňŐÕőŌ–—“”‘’÷◊ōŔŕŘ‹›řŖŗŠ‚„šŚśÁŤťÍŽžŪÓÔūŮÚůŰűŲųÝýķŻŁżĢˇ",
    cats: ASCII_CATS + "00100001101101101011010111111011AE0CAAA1EEE1DB1010BB10BB1010101010BB10B?@AF10010<<?@?@BE1010?@1010==1010010010001001010101100103",
  },
  "mac-roman": {
    singleByte: true,
    cps: ASCII_CPS + "ÄÅÇÉÑÖÜáàâäãåçéèêëíìîïñóòôöõúùûü†°¢£§•¶ß®©™´¨≠ÆØ∞±≤≥¥µ∂∑∏π∫ªºΩæø¿¡¬√ƒ≈∆«»… ÀÃÕŒœ–—“”‘’÷◊ÿŸ⁄€‹›ﬁﬂ‡·‚„‰ÂÊÁËÈÍÎÏÌÓÔÒÚÛÙıˆ˜¯˘˙˚¸˝˛ˇ",
    cats: ASCII_CATS + "00000001111111111111111111111111AECCAAA1EEEDDB00BBBBC1BBB1B44011AABB1BB?@AF00001<<?@?@BE10BC?@11AA==A00000000000L000013DDDDDDDD3",
  },
  "mac-turkish": {
    singleByte: true,
    cps: ASCII_CPS + "ÄÅÇÉÑÖÜáàâäãåçéèêëíìîïñóòôöõúùûü†°¢£§•¶ß®©™´¨≠ÆØ∞±≤≥¥µ∂∑∏π∫ªºΩæø¿¡¬√ƒ≈∆«»… ÀÃÕŒœ–—“”‘’÷◊ÿŸĞğİıŞş‡·‚„‰ÂÊÁËÈÍÎÏÌÓÔÒÚÛÙˆ˜¯˘˙˚¸˝˛ˇ",
    cats: ASCII_CATS + "00000001111111111111111111111111AECCAAA1EEEDDB00BBBBC1BBB1B44011AABB1BB?@AF00001<<?@?@BE10010101AA==A00000000000L0000L3DDDDDDDD3",
  },
  "ptcp154": {
    singleByte: true,
    cps: ASCII_CPS + "ҖҒӮғ„…ҶҮҲүҠӢҢҚҺҸҗ‘’“”•–—ҳҷҡӣңқһҹ ЎўЈӨҘҰ§Ё©Ә«¬ӯ®Ҝ°ұІіҙө¶·ё№ә»јҪҫҝАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя",
    cats: ASCII_CATS + "0001=A00010000001?@?@A<<11111111F010000A0E0?B1E0E10111AA1E1@10110000000000000000000000000000000011111111111111111111111111111111",
  },
  "shift_jis_2004": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[¥]^_`abcdefghijklmnopqrstuvwxyz{|}‾￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿｡｢｣､･ｦｧｨｩｪｫｬｭｮｯｰｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝﾞﾟ￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFAAACAAA=>ABA<AA8888888888AABBBAA00000000000000000000000000=C>D;D11111111111111111111111111=B>AIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMA=>AA4444444444344444444444444444444444444444444444444444444433MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "tis-620": {
    singleByte: true,
    cps: ASCII_CPS + "￿กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลฦวศษสหฬอฮฯะัาำิีึืฺุู￿￿￿￿฿เแโใไๅๆ็่้๊๋์ํ๎๏๐๑๒๓๔๕๖๗๘๙๚๛￿￿￿￿",
    cats: ASCII_CATS + "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIM4444444444444444444444444444444444444444444444445445555555MMMMC444444355555555A8888888888AAMMMM",
  },
  "utf-16": {
    singleByte: false,
    cps: "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-16-be": {
    singleByte: false,
    cps: "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-16-le": {
    singleByte: false,
    cps: "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-32": {
    singleByte: false,
    cps: "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-32-be": {
    singleByte: false,
    cps: "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-32-le": {
    singleByte: false,
    cps: "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-7": {
    singleByte: false,
    cps: "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&'()*￾,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFAAACAAA=>AMA<AA8888888888AABBBAA00000000000000000000000000=A>D;D11111111111111111111111111=B>BIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-8": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "utf-8-sig": {
    singleByte: false,
    cps: ASCII_CPS + "￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿￿",
    cats: ASCII_CATS + "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
  },
  "cp037": {
    singleByte: true,
    cps: "\u0000\u0001\u0002\u0003\t\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\b\u0018\u0019\u001c\u001d\u001e\u001f\n\u0017\u001b\u0005\u0006\u0007\u0016\u0004\u0014\u0015\u001a  âäàáãåçñ¢.<(+|&éêëèíîïìß!$*);¬-/ÂÄÀÁÃÅÇÑ¦,%_>?øÉÊËÈÍÎÏÌ`:#@'=\"Øabcdefghi«»ðýþ±°jklmnopqrªºæ¸Æ¤µ~stuvwxyz¡¿ÐÝÞ®^£¥·©§¶¼½¾[]¯¨´×{ABCDEFGHI­ôöòóõ}JKLMNOPQR¹ûüùúÿ\\÷STUVWXYZ²ÔÖÒÓÕ0123456789³ÛÜÙÚ",
    cats: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFF11111111CAB=BBA111111111ACA>AB<A00000000EAA;BA100000000DAAAABA0111111111?@111BE111111111441D0C1B11111111AA000EDCCAEAA:::=>DDDB=000000000J11111>000000000:11111AB00000000:000008888888888:0000I",
  },
});
