#!/usr/bin/env node
// Regenerates src/version.js from the version field in package.json so the
// bundled output exposes a `VERSION` constant matching whatever version is
// declared in package.json. Runs first from `npm run build` and
// `npm run build:bundles`, so any build reflects the current version.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const out = join(root, 'src', 'version.js');
const content =
  `// generated by scripts/sync-version.js — do not edit manually\n` +
  `// reflects the version field in package.json\n` +
  `export const VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(out, content, 'utf8');
console.log(`src/version.js → ${pkg.version}`);
