name: Build
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      - run: npm test
      - run: npm run test:browser
      - run: npm run build:bundles && npm run build:types
      - name: Check dist files match source
        env:
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          git diff --stat --no-color --exit-code \
          || (echo "dist files at $COMMIT_URL do not match source. Run 'npm run build && npm run build:bundles && npm run build:types' and commit." && exit 1)
